export const  titleArray = [
    'Shrek',
    'Batman',
    'American Pie',
    'The Godfather',
    'The Shawshank Redemption',
    'Pulp Fiction',
    'Star Wars',
    'Raiders of the Lost Ark',
    'Forrest Gump',
    'Apocalypse Now',
    'Goodfellas',
    'The Silence of the Lambs',
    'Jaws',
    'Blade Runner',
    'The Empire Strikes Back',
    'Fargo',
    'Badlands',
    'Boyz N the Hood',
    'Bullitt',
    'The Cameraman',
    'The Crowd',
    'The Deer Hunter',
    'Easy Rider',
    'The Endless Summer',
    'Field of Dreams',
    'Fury',
    'Ghostbusters',
    'King Kong',
    'Manhattan',
    'The Matrix',
    'Schindler’s List'
]